import { createFileRoute, Link } from "@tanstack/react-router";
import { Shield } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Pecto" },
      { name: "description", content: "Pecto Terms of Service." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="mx-auto flex max-w-4xl items-center justify-between px-6 py-6">
        <Link to="/" className="flex items-center gap-2">
          <Shield className="h-5 w-5 text-primary" />
          <span className="font-semibold tracking-tight">Pecto</span>
        </Link>
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground">
          Back to home
        </Link>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <h1 className="font-display text-4xl tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: July 27, 2026</p>

        <div className="prose prose-neutral dark:prose-invert mt-8 space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold">1. Acceptance of Terms</h2>
            <p className="mt-2 text-muted-foreground">
              By accessing or using Pecto ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">2. What Pecto Does</h2>
            <p className="mt-2 text-muted-foreground">
              Pecto is an AI-powered platform that helps you manage your online reputation by:
            </p>
            <ul className="mt-2 list-disc pl-6 text-muted-foreground">
              <li>Screening content you provide for reputational risk</li>
              <li>Generating draft responses for legitimate criticism</li>
              <li>Helping you create on-brand content</li>
              <li>Flagging potential impersonation or fake accounts</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold">3. What Pecto Does NOT Do</h2>
            <p className="mt-2 text-muted-foreground font-medium text-foreground">
              Pecto assists with legitimate content management — it does NOT suppress truthful information.
            </p>
            <ul className="mt-2 list-disc pl-6 text-muted-foreground">
              <li>We cannot and do not guarantee removal of third-party content</li>
              <li>We never help suppress content that is true, newsworthy, or a matter of public record</li>
              <li>We do not facilitate harassment, doxxing, or impersonation of others</li>
              <li>We are a defensive tool for managing YOUR reputation, not an offensive tool</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold">4. User Responsibilities</h2>
            <ul className="mt-2 list-disc pl-6 text-muted-foreground">
              <li>You are responsible for the content you submit for screening</li>
              <li>You must not use the Service to harm others</li>
              <li>You are responsible for maintaining the confidentiality of your account</li>
              <li>You must comply with all applicable laws when using remediation features</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold">5. AI-Generated Content</h2>
            <p className="mt-2 text-muted-foreground">
              Content generated by Pecto's AI (draft responses, brand posts) should be reviewed before
              publishing. AI outputs may contain inaccuracies and should not be treated as legal or professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">6. Limitation of Liability</h2>
            <p className="mt-2 text-muted-foreground">
              Pecto is provided "as is" without warranties. We are not liable for any damages arising from
              use of the Service, including but not limited to decisions made based on AI-generated recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">7. Changes to Terms</h2>
            <p className="mt-2 text-muted-foreground">
              We may update these terms from time to time. Continued use of the Service after changes constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold">8. Contact</h2>
            <p className="mt-2 text-muted-foreground">
               Questions about these Terms? Contact us through the Pecto support channel.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}